# Generated by Django 5.1.3 on 2024-11-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aboutimages_aboutus_appointment_classes_classesmain_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoGallery',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='title',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team'),
        ),
    ]
