# Generated by Django 5.1.3 on 2024-11-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_photogallery_rename_description_team_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teams_blocks')),
                ('social_title1', models.CharField(blank=True, max_length=50, null=True)),
                ('social_title2', models.CharField(blank=True, max_length=50, null=True)),
                ('social_title3', models.CharField(blank=True, max_length=50, null=True)),
                ('social_url1', models.URLField(blank=True, max_length=255)),
                ('social_url2', models.URLField(blank=True, max_length=255)),
                ('social_url3', models.URLField(blank=True, max_length=255)),
                ('social_html_class1', models.CharField(blank=True, max_length=200, null=True)),
                ('social_html_class2', models.CharField(blank=True, max_length=200, null=True)),
                ('social_html_class3', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Team Blocks',
                'verbose_name_plural': 'Team Blocks',
            },
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
