# Generated by Django 5.1.3 on 2024-11-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contactblocks_contactusmain_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
